# Springdoc配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
  group-configs:
    - group: 'default'
      display-name: '测试模块'
      paths-to-match: '/**'
      packages-to-scan: com.zhglxt.web.controller.tool
    - group: 'cms'
      display-name: '企业官网'
      paths-to-match: '/cms/**'
      packages-to-scan: com.zhglxt.web.controller