# 项目相关配置
zhglxt:
  # 名称
  name: 综合管理系统
  # 版本
  version: 4.8.1
  # 版权年份
  copyrightYear: 2025
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/zhglxt/uploadPath，Linux配置 /home/zhglxt/uploadPath）
  profile: D:/zhglxt/uploadPath
  # 获取ip地址开关
  addressEnabled: false

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8888
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /zhglxt
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
 
# 日志配置
logging:
  level:
    com.zhglxt: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid,mybatis,shiro,doc
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 50MB
      # 设置总上传的文件大小
      max-request-size: 100MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
      # 配置需要实时更新的目录
      additional-paths:
        - src/main/resources
        - src/main/static
        - src/main/templates

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*,/oa/notify/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 防止csrf攻击
csrf:
  # 过滤开关
  enabled: false
  # 白名单（多个用逗号分隔）
  whites: /druid